import '../styles/globals.css'
import { Layout } from '../layout/layout'
import Head from 'next/head'
import { UserContextProvider } from '../contexts/userContext/userContext'
import { ThemeContextProvider } from '../contexts/themeContext/themeContext'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { useState } from 'react'
import { AppProps } from 'next/app'

export default function MyApp({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient())

  return (
    <QueryClientProvider client={queryClient}>
      <UserContextProvider>
        <ThemeContextProvider>
          <Layout>
            <Head>
              <title>Serve</title>
              <meta name='description' content='Generated by create next app' />
              <link rel='icon' href='/favicon.ico' />
            </Head>
            <Component {...pageProps} />
            {/* <ReactQueryDevtools /> */}
          </Layout>
        </ThemeContextProvider>
      </UserContextProvider>
    </QueryClientProvider>
  )
}
